### ISSUE TITLE
Accuracy tradeoff

### ISSUE THREAD

**Issue by williamhoole** [Kolkir/Coarse_LoFTR_TRT#11]
Hi, does anyone now what the accuracy tradeoff is between the original loftr and the coarse loftr?

**Comment by Kolkir** [comment]
Hi for the coarse loftr accuracy will be much lower.

**Comment by Kolkir** [comment]
You can take a look on the recent work, it should be more interesting https://zju3dv.github.io/efficientloftr/

**Comment by williamhoole** [comment]
Thank you! I am currently doing some research with the goal of deploying a feature matching model on a jetson Orin that is able to match features with large rotation. I have tested your model and it definitely has the inference speed I need however i will have to train the model on my own data that has large rotations.

**Comment by williamhoole** [comment]
Do you know if it is possible to export efficient loftr to ONNX and also optimize with tensorrt to run on a Nvidia Jetson?

**Comment by Kolkir** [comment]
Unfortunately I didn't try yet.

**Comment by williamhoole** [comment]
Thank you so much for your responses @Kolkir! It is very helpful for me. I find feature matching to be quite a complex task in Computer Vision. My goal is to deploy a Feature Matching model on a Jetson Xavier that will match features from 2 images with size 256x256. I know your model is capable of being optimized with TensorRT because it doesn't have dynamic tensors.

Now I was wondering, because this model does the coarse matching part of LofTR, if I decrease the downscale resolution to 4 my dimension at coarse level matching will be (256x256 --> 64x64) as apposed to 32x32.

If I compare this size to the image size you used it has a similar dimension at coarse matching (640x480 --> 80x60).  

If I were to decrease the downscale factor from 8-->4 I could possible achieve higher accuracy. The model will be slower at Inference but because i am already using small input images it wont be significant.

Do you think it could make sense to decrease the downscale factor for my situation?

**Comment by sunfan1997** [comment]
> Hi, does anyone now what the accuracy tradeoff is between the original loftr and the coarse loftr?


I used the evaluation metrics and code from the original project. The original project achieved a prec@5e-04 of 0.88, whereas this project only reached 0.37.
