### ISSUE TITLE
trt file running error

### ISSUE THREAD

**Issue by ZDLLLL** [Kolkir/Coarse_LoFTR_TRT#4]
![image](https://user-images.githubusercontent.com/44689801/175457648-7b7dfe2d-e7b1-4c7a-8a56-40da98fc05ad.png)
When I use the trt method to run webcam.py, I encounter the above error, how can I solve it

**Comment by aybora** [comment]
Hi, I encountered the exact same error, how did you solve it?

**Comment by ZDLLLL** [comment]
> 

You need to regenerate the trt file according to the file he gave

**Comment by YJonmo** [comment]
I created the onnx weight using the export_onnx.py and tested the .onnx weight and it worked. But when I used the export_trt.py and loaded the .trt weights, it didn't work.
