### ISSUE TITLE
fine level matching

### ISSUE THREAD

**Issue by chicleee** [Kolkir/Coarse_LoFTR_TRT#5]
hi @Kolkir , nice work!
Could you explain why you didn't keep the fine level matching in this work? Is it difficult to achieve?

**Comment by Kolkir** [comment]
Hi @chicleee the main idea of this project was to create a network that can be used on edge devices with a reasonable performance. So the knowledge distillation was used, to reduce the size. The  fine level matching part is the most resource consuming one, that is why it was excluded. Also, there are technical reasons that make it hard to move to TensorRT - it contains dynamic tensor shapes.

**Comment by chicleee** [comment]
I see, thanks a lot.

**Comment by ynma-hanvo** [comment]
thanks.   as you mention:  it contains dynamic tensor shapes.      if we have fix input images sizes , will it be doable to convert whole network into trt;

**Comment by Kolkir** [comment]
@ynma-hanvo the problem is that dynamic shapes comes from the number of features detected in the coarse module. The one of possible solution is to make fixed number of features and somehow to mark the ones that are missed.
